### ISSUE TITLE
docusaurus v3 support?

### ISSUE THREAD

**Issue by einarkolsen** [karser/docusaurus-plugin-matomo#5]
Hi, will there be v3 support for this?

**Comment by Battleman** [comment]
Added in v0.0.8 (see 31787e4)

**Comment by pmig** [comment]
@karser maybe it makes sense to also update the about section:

![image](https://github.com/karser/docusaurus-plugin-matomo/assets/3041752/04a2f934-c992-4010-9d59-22cb786cb11d)

**Comment by karser** [comment]
thanks @pmig , done
